### ISSUE TITLE
buttons not working.

### ISSUE THREAD

**Issue by ghost** [jimkeir/EDProxy#1]
All is in the title, no buttons working, clicking them does nothing.

**Comment by Slipi089** [comment]
+1

**Comment by jimkeir** [comment]
I've tested this and it seems OK. Can you be a bit clearer? What buttons - start? stop? Something in settings? Also, can you please confirm the version you're using?

**Comment by Slipi089** [comment]
my settings button and the start button do not work - when they are pressed, nothing happens.
(Release 242 & 240 tested with both versions)

**Comment by jimkeir** [comment]
I've tested 2.4.2 and it starts OK here. Could you post the logfile "%USERPROFILE%\.edproxy\edproxy.log" and confirm what O/S you're using, please?

**Comment by Slipi089** [comment]
Win10

[edproxy.log](https://github.com/jimkeir/EDProxy/files/4058712/edproxy.log)

**Comment by jimkeir** [comment]
Thanks for the log. There is a problem when EDProxy can't find Elite:Dangerous at all on your PC. I've fixed this and made it clearer that the problem exists, and will upload a build either later today or tomorrow to fix this. In the meantime, if you edit edproxy.ini (same location as the log), and put in the correct values for [NetLog] path, [NetLog] appconfig_path and [Journal] path, it should start up.
